Update MainView.swift
PlayCover/PlayCover pull request #1060
Opened 2023-07-28 11:08 UTC by 404oops

I saw a major design oversight regarding the sidebar button.

https://github.com/PlayCover/PlayCover/assets/51266541/f6db7c05-7218-41ba-9113-de200a06894b

The Sidebar button is positioned to `.navigation` which doesn't really make sense since the user needs to chase it if they misclick.

I removed the position so that it sticks to default (left side)

https://github.com/PlayCover/PlayCover/assets/51266541/348e45e3-8004-4393-9ef7-195c69303cc7

The code for this entry can be found [here](https://github.com/404oops/NamecheapDDNS/blob/507021107872c1ffacf3ae7a8c04e75e8e7b5c6e/NamecheapDDNS/ContentView.swift#L38-L45) as "proof" that it works

2023-07-28 17:37 UTC, amirsaam approved these changes

2023-07-28 17:39 UTC, amirsaam requested changes
please fix the plus button position to not stick to left side and stay where it should stay if your change affected it.

2023-07-28 19:30 UTC, 404oops commented
Read the code, my change only affected the sidebar button.

2023-08-14 21:57 UTC, zyxkad commented
> Read the code, my change only affected the sidebar button.

Just record video with the compiled version next time, don't just pick random app to show or let us guess how should it work

2023-09-25 21:46 UTC, JoseMoreville approved these changes

2023-09-25 21:47 UTC, merged