Issue template updates
PlayCover/PlayCover pull request #204
Opened 2022-08-19 20:53 UTC by IsaacMarovitz

2022-08-19 20:57 UTC, Depal1 requested changes
The game support area could be improved further to make reviews easier.
`Did the app install correctly? -> Does it load without crashing? -> Does it crash in-game with a known trigger?`

2022-08-19 21:01 UTC, Candygoblen123 requested changes

2022-08-19 21:01 UTC, Candygoblen123 commented on .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
> +title: "[FR]: "
can you make this `[Feature]: ` or `[Feat]: `

2022-08-19 21:01 UTC, Candygoblen123 commented on .github/ISSUE_TEMPLATE/GAME-SUPPORT.yml
> +title: "[GS]: "
can you change this to `[Game Support]: `

2022-08-19 21:10 UTC, Depal1 approved these changes

2022-08-19 21:11 UTC, Candygoblen123 approved these changes

2022-08-19 21:12 UTC, merged

2022-08-20 04:27 UTC, danielrominger46 reviewed
Testes