Improve Xcode Command line tools install UX
PlayCover/PlayCover pull request #250
Opened 2022-08-26 15:00 UTC by Candygoblen123

Improves Xcode command line tools detection by actually checking if the files are there, regardless of what `xcode-select -p` tells us

Improve the UI by:
- Adding icons for preinstall, success, and failure steps
- Playing a sound on successful and errored install
- Provide a link to alternate install methods on failure
- After install finishes, actually check to make sure that the Command Line tools were installed, and show the error screen if they aren't.

Screenshots: 
<img width="1061" alt="Screen Shot 2022-08-26 at 10 15 42 AM" src="https://user-images.githubusercontent.com/28193374/186934502-83ba30b7-5b49-4be3-b13a-82c21d04c834.png">
<img width="1061" alt="Screen Shot 2022-08-26 at 10 16 29 AM" src="https://user-images.githubusercontent.com/28193374/186934510-980af497-090b-406d-ac07-bd284dbfc674.png">
<img width="1061" alt="Screen Shot 2022-08-26 at 10 17 20 AM" src="https://user-images.githubusercontent.com/28193374/186934514-f86d3b79-25bf-4b03-88e1-b3f235d995ce.png">
<img width="1061" alt="Screen Shot 2022-08-26 at 10 15 37 AM" src="https://user-images.githubusercontent.com/28193374/186934517-78bfce7e-ba54-498f-9b67-2c4085aa807c.png">

2022-08-29 15:03 UTC, IsaacMarovitz approved these changes

2022-08-29 15:08 UTC, Depal1 requested changes
There are conflicts that need to be resolved before merging.

2022-08-29 20:54 UTC, Depal1 commented
https://github.com/PlayCover/PlayCover/pull/250/commits/5c4492453fe55deba108601f99abf94fdcc9876c is reverting changes from #258 and #262.

2022-08-30 09:38 UTC, Lakr233 commented
I have done similar design/stuff, could copy mine if you want :)

<img width="865" alt="截屏2022-08-30 17 35 49" src="https://user-images.githubusercontent.com/25259084/187403442-1d639518-6103-4eda-82bf-45ae3648abc9.png">

https://lab.qaq.wiki/Lakr233/ActionBee/-/blob/2d3e6b67866215c6ca6e088dae79ff73b12333aa/App/Action/Action/Interface/Generic/XcodeTestView.swift

2022-08-30 20:48 UTC, Depal1 approved these changes

2022-08-30 20:48 UTC, merged