Force RTL while Language is RTL
PlayCover/PlayCover pull request #387
Opened 2022-09-30 15:57 UTC by amirsaam

To clarify, when you use a RTL locale as PlayCover's app specific language it will show as RTL perfectly but beside Arabic that macOS itself is translated into, if you choose any other RTL language as System's Preferred Language (for e.g. Persian), only PlayCover's language will change but not the layout.
As far as I knew about SwiftUI I managed to force the layout to become RTL but I dunno where and why, other things beside the MainView are declining the layout change.
<img width="1012" alt="Screenshot_1401-07-07_at_04 58 24" src="https://user-images.githubusercontent.com/1331289/193309670-acac25d3-a6a8-46e0-bf2a-7175c2ef8176.png">

2022-09-30 19:56 UTC, JoseMoreville requested changes

2022-09-30 19:56 UTC, JoseMoreville commented on PlayCover/Views/PlayCoverApp.swift
> +    if rtlLangs.contains(langCode!) { return true } else { return false }
You can simplify this line by returning boolean computation

2022-09-30 20:10 UTC, amirsaam commented on PlayCover/Views/PlayCoverApp.swift
> +    if rtlLangs.contains(langCode!) { return true } else { return false }
done.

2022-10-09 11:01 UTC, amirsaam commented
Ok, updated the PR information with details.
@Depal1 can you please add `help-wanted` tag?

2022-10-09 18:17 UTC, zanderp25 commented
> can you please add `help-wanted` label to this pr?

I gotchu

2022-10-09 18:46 UTC, zanderp25 commented
Okay, so i tested a few things:

> Genshin Impact account manager views need to be tested (I don't have it) `*`

I built your PR on my computer after setting the language to Arabic and I tested the account views on Genshin

<img width="1012" alt="‏لقطة الشاشة ٢٠٢٢-١٠-٠٩ في ١٤ ٢٧ ٣٥" src="https://user-images.githubusercontent.com/13000207/194773633-9788f342-05fd-467e-83b0-1748fa0313ad.png">
<img width="968" alt="‏لقطة الشاشة ٢٠٢٢-١٠-٠٩ في ١٤ ٣٣ ١٦" src="https://user-images.githubusercontent.com/13000207/194773647-afa07a6b-7728-4c8d-8ea8-fcb1284c39f6.png">

It looks fine to me

> AppSetting view's TabView is not ordered from Right to Left

Looks fine to me

<img width="1012" alt="‏لقطة الشاشة ٢٠٢٢-١٠-٠٩ في ١٤ ٢٨ ٤٢" src="https://user-images.githubusercontent.com/13000207/194773717-fd7a9d13-cd1a-40bd-b924-8b26618e4da2.png">

> Menubar items not RTL (very low priority, maybe never fix it because its language is mixed)

This also looks fine to me

<img width="254" alt="‏لقطة الشاشة ٢٠٢٢-١٠-٠٩ في ١٤ ٤١ ٤٥" src="https://user-images.githubusercontent.com/13000207/194774018-d1c92009-4833-4912-86f6-87001794a49e.png">

2022-10-10 01:45 UTC, amirsaam commented
Thanks @zanderp25 but like I said:

> Only known RTL language that macOS has translation is Arabic, never test apps under this language for RTL compatibility.

I appreciate what you have done.

2022-10-10 14:23 UTC, zanderp25 commented
> Only known RTL language that macOS has translation is Arabic, never test apps under this language for RTL compatibility.

Why not? I didn't reboot my computer so it only changes the language of programs that are relaunched after the change.

2022-10-10 19:29 UTC, amirsaam commented
> Why not? I didn't reboot my computer so it only changes the language of programs that are relaunched after the change.

Well, because macOS itself has been translated to Arabic and Hebrew (I didn't know about this one) the whole system becomes rtl and cuz of that you'll see no problem on ui, but other languages that have no translation for macOS will have a lot of problems; test it under Persian, you'll see.

2022-10-13 09:38 UTC, closed without merging