Code cleanup + Styling Fixes
PlayCover/PlayCover pull request #417
Opened 2022-10-12 02:32 UTC by IsaacMarovitz

2022-10-17 20:07 UTC, Candygoblen123 requested changes, later dismissed

2022-10-17 20:07 UTC, Candygoblen123 commented on PlayCover/Utils/ImageCache.swift
> +class ImageCache {
There isn't much of a reason to implement our own image cache when implementations like https://github.com/lorenzofiamingo/swiftui-cached-async-image already exist.

2022-10-17 20:07 UTC, Candygoblen123 commented on PlayCover/Utils/ImageCache.swift
> +    static let cacheFolder = PlayTools.playCoverContainer.appendingPathComponent("Image Cache")
Instead of chucking everything into a folder, we should use the system cache.

2022-10-17 20:07 UTC, Candygoblen123 commented on PlayCover/Utils/ImageCache.swift
> +            return saveImageToCache(image: bestResImage!, bundleID: bundleID)
Why are we caching images that already exist on disk?

2022-10-19 04:37 UTC, Depal1 approved these changes

2022-10-19 17:46 UTC, merged