Various fixes
PlayCover/PlayCover pull request #759
Opened 2023-01-30 15:03 UTC by IsaacMarovitz

- Save Metal HUD state (closes #526)
- Add PlayChain to the uninstaller
- Sort libraries alphabetically

2023-02-01 03:26 UTC, Depal1 requested changes

2023-02-01 03:26 UTC, Depal1 commented on PlayCover/ViewModel/AppsVM.swift
> +        filteredApps.sort(by: { $0.name < $1.name })
Sorting should be case insensitive.

2023-02-01 03:26 UTC, Depal1 commented on PlayCover/Views/Uninstaller.swift
> +                ("removePlayChain", NSLocalizedString("preferences.toggle.removePlayChain", comment: ""))
The disposition of the items is not being kept.
![Screenshot 2023-01-31 at 20 29 28](https://user-images.githubusercontent.com/47154119/215934285-af54b7aa-4c4c-4d62-adb1-06afe0318430.png)
![Screenshot 2023-01-31 at 20 29 15](https://user-images.githubusercontent.com/47154119/215934292-faff05b7-7d27-4814-ad8b-158e6a8b597c.png)

2023-02-01 03:32 UTC, TheMoonThatRises commented on PlayCover/Views/Settings/UninstallSettings.swift
> +    @objc @AppStorage("RemovePlayChain") var removePlayChain = false
The key for the App Storage should have the `Uninstall` prefix to maintain the uninstall setting naming convention.

2023-02-10 21:31 UTC, TheMoonThatRises approved these changes

2023-02-12 14:09 UTC, Depal1 approved these changes

2023-02-12 14:10 UTC, merged