Translations update from Hosted Weblate
PlayCover/PlayCover pull request #764
Opened 2023-01-31 08:49 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [PlayCover/PlayCover](https://hosted.weblate.org/projects/playcover/playcover/).

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/playcover/-/playcover/horizontal-auto.svg)

2023-02-02 02:51 UTC, Depal1 requested changes

2023-02-02 02:51 UTC, Depal1 commented on PlayCover/es.lproj/Localizable.strings
> +"playapp.progress.failed" = "Fallida";
The Spanish locale will require scrutiny again.

2023-02-10 13:22 UTC, IsaacMarovitz approved these changes
Merging since locales are quite out of date rn

2023-02-12 16:05 UTC, Depal1 approved these changes

2023-02-12 16:05 UTC, merged