Add localization in app
PlayCover/PlayCover pull request #807
Opened 2023-02-15 19:35 UTC by XuYicong

Copies translations of playtools text into the installed app, whenever AKInterface is copied.

So that playtools can find them at runtime and display contents in the user's preferred language.

2023-02-15 19:42 UTC, IsaacMarovitz requested changes

2023-02-15 19:42 UTC, IsaacMarovitz commented on PlayCover/Utils/PlayTools.swift
> +                          componet: String, pathExtension: String) throws -> URL {
`component`

2023-02-15 19:48 UTC, IsaacMarovitz approved these changes

2023-03-16 14:19 UTC, IsaacMarovitz commented
@XuYicong Needs a rebase

2023-03-17 09:03 UTC, XuYicong commented
Conflicts resolved

2023-04-12 05:40 UTC, merged